/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab06;

/**
 *
 * @author Daniel
*/
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Lab06GUI extends javax.swing.JFrame {

    /**
     * Creates new form Lab06GUI
     */
    public Lab06GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ArrayList<Student> People = new ArrayList(); 
    String type = ""; 
    public void safeExit() {
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0); 
        }
    }
    public void clear() {
        txt_FName.setText(""); 
        txt_MInit.setText("");
        txt_LName.setText("");
        txt_PUID.setText("");
        txt_Address.setText("");
        txt_State.setText("");
        cbo_Zip.setSelectedIndex(-1); 
        cbo_Country.setSelectedIndex(-1); 
        cbo_Major.setSelectedIndex(-1); 
        cbo_College.setSelectedIndex(-1); 
        txt_College.setText("");
        rad_Thesis.setSelected(false); 
        rad_NonThesis.setSelected(false);
        rad_MS.setSelected(false);
        rad_PhD.setSelected(false);        
    }
    public void setUneditable() {
        txt_FName.setEditable(false); 
        txt_MInit.setEditable(false);
        txt_LName.setEditable(false); 
        txt_PUID.setEditable(false); 
        txt_Address.setEditable(false);
        txt_State.setEditable(false);
        cbo_Zip.setEditable(false);
        cbo_Country.setEditable(false); 
        cbo_Major.setEditable(false);
        cbo_College.setEditable(false);
        txt_College.setEditable(false);
        rad_Thesis.setEnabled(false); 
        rad_NonThesis.setEnabled(false); 
        rad_MS.setEnabled(false);
        rad_PhD.setEnabled(false);
    }
    public void setUndergrad() {
        txt_FName.setEditable(true); 
        txt_MInit.setEditable(true);
        txt_LName.setEditable(true); 
        txt_PUID.setEditable(true); 
        txt_Address.setEditable(true);
        txt_State.setEditable(true);
        cbo_Zip.setEditable(false);
        cbo_Country.setEditable(false); 
        cbo_Major.setEditable(false);
        cbo_College.setEditable(false);
        txt_College.setEditable(false);
        rad_Thesis.setEnabled(false); 
        rad_NonThesis.setEnabled(false); 
        rad_MS.setEnabled(false);
        rad_PhD.setEnabled(false);
    }
    public void setGrad() {
        txt_FName.setEditable(true); 
        txt_MInit.setEditable(true);
        txt_LName.setEditable(true); 
        txt_PUID.setEditable(true); 
        txt_Address.setEditable(true);
        txt_State.setEditable(true);
        cbo_Zip.setEditable(false);
        cbo_Country.setEditable(false); 
        cbo_Major.setEditable(false);
        cbo_College.setEditable(false);
        txt_College.setEditable(false);
        rad_Thesis.setEnabled(true); 
        rad_NonThesis.setEnabled(true); 
        rad_MS.setEnabled(true);
        rad_PhD.setEnabled(true);
    }
    public void setNonDegree() {
        txt_FName.setEditable(true); 
        txt_MInit.setEditable(true);
        txt_LName.setEditable(true); 
        txt_PUID.setEditable(true); 
        txt_Address.setEditable(true);
        txt_State.setEditable(true);
        cbo_Zip.setEditable(false);
        cbo_Country.setEditable(false); 
        cbo_Major.setEditable(false);
        cbo_College.setEditable(false);
        txt_College.setEditable(true);
        rad_Thesis.setEnabled(false); 
        rad_NonThesis.setEnabled(false); 
        rad_MS.setEnabled(false);
        rad_PhD.setEnabled(false);
    }
    
    public void save() {
        if (type.equals("Undergrad")) {
            Undergrad a = new Undergrad(txt_FName.getText(), txt_MInit.getText().charAt(0), txt_LName.getText(), Integer.parseInt(txt_PUID.getText()),
            txt_Address.getText(), txt_State.getText(), Integer.parseInt(cbo_Zip.getSelectedItem().toString()), cbo_Country.getSelectedItem().toString(), 
                    cbo_Major.getSelectedItem().toString());
            People.add(a); 
        }
        else if (type.equals("Graduate")) {
            Graduate a = new Graduate(txt_FName.getText(), txt_MInit.getText().charAt(0), txt_LName.getText(), Integer.parseInt(txt_PUID.getText()),
            txt_Address.getText(), txt_State.getText(), Integer.parseInt(cbo_Zip.getSelectedItem().toString()), cbo_Country.getSelectedItem().toString(), 
                    cbo_Major.getSelectedItem().toString(), rad_Thesis.isSelected(), rad_MS.isSelected());
            People.add(a); 
        }
        else if (type.equals("NonDegree")) {
            String college; 
            
            if (txt_College.getText().equals("")) {
                college = (String)cbo_College.getSelectedItem(); 
            }
            else {
                college = txt_College.getText(); 
                cbo_College.addItem(college); 
            }
            NonDegree a = new NonDegree(txt_FName.getText(), txt_MInit.getText().charAt(0), txt_LName.getText(), Integer.parseInt(txt_PUID.getText()),
            txt_Address.getText(), txt_State.getText(), Integer.parseInt(cbo_Zip.getSelectedItem().toString()), cbo_Country.getSelectedItem().toString(), 
                    college);
            
            People.add(a); 
        }
    }
    
    public void execute() {
        int a = Integer.parseInt(txt_PUID.getText()); 
        Student hold = null; 
        for (Student s : People) {
            if (s.PUID == a) {
                hold = s; 
                break; 
            }
        }
        
        if (hold != null) {
            if (hold instanceof Graduate) {
                Graduate d = (Graduate) hold; 
                txt_FName.setText(hold.firstName); 
                txt_MInit.setText(Character.toString(hold.mInit));
                txt_LName.setText(hold.lastName); 
                txt_PUID.setText(Integer.toString(hold.PUID)); 
                txt_Address.setText(hold.Address); 
                txt_State.setText(hold.state); 
                cbo_Zip.setSelectedItem(Integer.toString(hold.zip)); 
                cbo_Country.setSelectedItem(hold.country); 
                
                cbo_Major.setSelectedItem(d.major); 
                if (d.Thesis == true) {
                    rad_Thesis.setSelected(true); 
                }
                else 
                    rad_NonThesis.setSelected(false); 
                if (d.MS == true) {
                    rad_MS.setSelected(true); 
                }
                else 
                    rad_PhD.setSelected(true);
                
                setGrad(); 
            }
            else if (hold instanceof Undergrad) {
                Undergrad d = (Undergrad) hold; 
                txt_FName.setText(hold.firstName); 
                txt_MInit.setText(Character.toString(hold.mInit));
                txt_LName.setText(hold.lastName); 
                txt_PUID.setText(Integer.toString(hold.PUID)); 
                txt_Address.setText(hold.Address); 
                txt_State.setText(hold.state); 
                cbo_Zip.setSelectedItem(Integer.toString(hold.zip)); 
                cbo_Country.setSelectedItem(hold.country); 
                
                cbo_Major.setSelectedItem(d.major); 
                
                setUndergrad(); 
            }
            else if (hold instanceof NonDegree) {
                NonDegree d = (NonDegree) hold; 
                txt_FName.setText(hold.firstName); 
                txt_MInit.setText(Character.toString(hold.mInit));
                txt_LName.setText(hold.lastName); 
                txt_PUID.setText(Integer.toString(hold.PUID)); 
                txt_Address.setText(hold.Address); 
                txt_State.setText(hold.state); 
                cbo_Zip.setSelectedItem(Integer.toString(hold.zip)); 
                cbo_Country.setSelectedItem(hold.country); 
                
                cbo_College.setSelectedItem(d.College); 
                
                // txt_College.setText(d.College); 
                
                setNonDegree(); 
            }
            People.remove(hold); 
        }
        else {
            JOptionPane.showMessageDialog(null, "No Record Found"); 
        }
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        btn_Grp_Thesis = new javax.swing.ButtonGroup();
        btn_Grp_Degree = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jTB_Exit = new javax.swing.JButton();
        jTB_Clear = new javax.swing.JButton();
        jTB_Save = new javax.swing.JButton();
        jTB_Execute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_FName = new javax.swing.JTextField();
        txt_MInit = new javax.swing.JTextField();
        txt_LName = new javax.swing.JTextField();
        txt_PUID = new javax.swing.JTextField();
        txt_Address = new javax.swing.JTextField();
        txt_State = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rad_MS = new javax.swing.JRadioButton();
        rad_PhD = new javax.swing.JRadioButton();
        rad_Thesis = new javax.swing.JRadioButton();
        rad_NonThesis = new javax.swing.JRadioButton();
        cbo_Zip = new javax.swing.JComboBox();
        cbo_Country = new javax.swing.JComboBox();
        cbo_Major = new javax.swing.JComboBox();
        cbo_College = new javax.swing.JComboBox();
        txt_College = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnu_New_Undergrad = new javax.swing.JMenuItem();
        mnu_New_Graduate = new javax.swing.JMenuItem();
        mnu_New_NonDegree = new javax.swing.JMenuItem();
        mnu_File_Save = new javax.swing.JMenuItem();
        mnu_File_Clear = new javax.swing.JMenuItem();
        mnu_File_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnu_Query_Enter = new javax.swing.JMenuItem();
        mnu_Query_Execute = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnu_Help_About = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Record Database");
        setBounds(new java.awt.Rectangle(0, 0, 600, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 600));

        jToolBar1.setRollover(true);

        jTB_Exit.setText("Exit");
        jTB_Exit.setFocusable(false);
        jTB_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTB_Exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTB_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTB_ExitActionPerformed(evt);
            }
        });
        jToolBar1.add(jTB_Exit);

        jTB_Clear.setText("Clear");
        jTB_Clear.setFocusable(false);
        jTB_Clear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTB_Clear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTB_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTB_ClearActionPerformed(evt);
            }
        });
        jToolBar1.add(jTB_Clear);

        jTB_Save.setText("Save");
        jTB_Save.setFocusable(false);
        jTB_Save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTB_Save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTB_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTB_SaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jTB_Save);

        jTB_Execute.setText("Execute");
        jTB_Execute.setFocusable(false);
        jTB_Execute.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTB_Execute.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTB_Execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTB_ExecuteActionPerformed(evt);
            }
        });
        jToolBar1.add(jTB_Execute);

        jLabel1.setText("First Name:");

        jLabel2.setText("Middle Init:");

        jLabel3.setText("Last Name: ");

        jLabel4.setText("PUID: ");

        jLabel5.setText("Address: ");

        jLabel6.setText("State:");

        txt_FName.setEditable(false);
        txt_FName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_MInit.setEditable(false);
        txt_MInit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_LName.setEditable(false);
        txt_LName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_PUID.setEditable(false);
        txt_PUID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_Address.setEditable(false);
        txt_Address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_State.setEditable(false);
        txt_State.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_StateActionPerformed(evt);
            }
        });

        jLabel7.setText("Zip Code:");

        jLabel8.setText("Country: ");

        jLabel9.setText("Major:");

        jLabel10.setText("College: ");

        jLabel11.setText("Thesis or Non-Thesis: ");

        jLabel12.setText("MS or PhD: ");

        btn_Grp_Degree.add(rad_MS);
        rad_MS.setText("MS");
        rad_MS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rad_MS.setEnabled(false);

        btn_Grp_Degree.add(rad_PhD);
        rad_PhD.setText("PhD");
        rad_PhD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rad_PhD.setEnabled(false);

        btn_Grp_Thesis.add(rad_Thesis);
        rad_Thesis.setText("Thesis");
        rad_Thesis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rad_Thesis.setEnabled(false);
        rad_Thesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_ThesisActionPerformed(evt);
            }
        });

        btn_Grp_Thesis.add(rad_NonThesis);
        rad_NonThesis.setText("Non-Thesis");
        rad_NonThesis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rad_NonThesis.setEnabled(false);

        cbo_Zip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "47906", "46247", "46227", "32145", "56790" }));
        cbo_Zip.setSelectedIndex(-1);
        cbo_Zip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbo_Country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "United States", "UAE", "Dubai", "Egypt", "Kenya", "Japan", "China", "South Korea", "Germany", "France" }));
        cbo_Country.setSelectedIndex(-1);
        cbo_Country.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbo_Major.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CNIT", "ECET", "IE", "BME", "EE" }));
        cbo_Major.setSelectedIndex(-1);
        cbo_Major.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbo_College.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_College.setEditable(false);
        txt_College.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("File");

        jMenu4.setText("New");

        mnu_New_Undergrad.setText("Undergrad");
        mnu_New_Undergrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_New_UndergradActionPerformed(evt);
            }
        });
        jMenu4.add(mnu_New_Undergrad);

        mnu_New_Graduate.setText("Graduate");
        mnu_New_Graduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_New_GraduateActionPerformed(evt);
            }
        });
        jMenu4.add(mnu_New_Graduate);

        mnu_New_NonDegree.setText("Non-Degree");
        mnu_New_NonDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_New_NonDegreeActionPerformed(evt);
            }
        });
        jMenu4.add(mnu_New_NonDegree);

        jMenu1.add(jMenu4);

        mnu_File_Save.setText("Save");
        mnu_File_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_File_SaveActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_File_Save);

        mnu_File_Clear.setText("Clear");
        jMenu1.add(mnu_File_Clear);

        mnu_File_Exit.setText("Exit");
        mnu_File_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_File_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_File_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Query");

        mnu_Query_Enter.setText("Enter");
        mnu_Query_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_Query_EnterActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_Query_Enter);

        mnu_Query_Execute.setText("Execute");
        mnu_Query_Execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_Query_ExecuteActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_Query_Execute);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        mnu_Help_About.setText("About");
        mnu_Help_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_Help_AboutActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_Help_About);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rad_MS)
                                .addGap(36, 36, 36)
                                .addComponent(rad_PhD))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rad_Thesis)
                                .addGap(18, 18, 18)
                                .addComponent(rad_NonThesis))))
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_LName)
                                    .addComponent(txt_MInit)
                                    .addComponent(txt_FName)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(51, 51, 51)
                                .addComponent(txt_PUID))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(txt_Address))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_College, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_State)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbo_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbo_Zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cbo_College, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbo_Major, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(0, 66, Short.MAX_VALUE)))))
                        .addGap(112, 112, 112)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_PUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_Zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_Major, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbo_College, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_College, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rad_Thesis)
                    .addComponent(rad_NonThesis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rad_MS)
                    .addComponent(rad_PhD))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_File_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_File_ExitActionPerformed
        safeExit(); 
    }//GEN-LAST:event_mnu_File_ExitActionPerformed

    private void jTB_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTB_ExitActionPerformed
        safeExit();
    }//GEN-LAST:event_jTB_ExitActionPerformed

    private void txt_StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StateActionPerformed

    private void rad_ThesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_ThesisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_ThesisActionPerformed

    private void jTB_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTB_ClearActionPerformed
        clear(); 
        setUneditable(); 
    }//GEN-LAST:event_jTB_ClearActionPerformed

    private void mnu_New_UndergradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_New_UndergradActionPerformed
        setUndergrad();  
        type = "Undergrad"; 
    }//GEN-LAST:event_mnu_New_UndergradActionPerformed

    private void mnu_New_GraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_New_GraduateActionPerformed
        setGrad();
        type = "Graduate"; 
    }//GEN-LAST:event_mnu_New_GraduateActionPerformed

    private void mnu_New_NonDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_New_NonDegreeActionPerformed
        setNonDegree(); 
        type = "NonDegree"; 
    }//GEN-LAST:event_mnu_New_NonDegreeActionPerformed

    private void jTB_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTB_SaveActionPerformed
        save(); 
    }//GEN-LAST:event_jTB_SaveActionPerformed

    private void mnu_File_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_File_SaveActionPerformed
        save();
    }//GEN-LAST:event_mnu_File_SaveActionPerformed

    private void mnu_Query_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_Query_EnterActionPerformed
        clear(); 
        setUneditable(); 
        txt_PUID.setEditable(true); 
    }//GEN-LAST:event_mnu_Query_EnterActionPerformed

    private void jTB_ExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTB_ExecuteActionPerformed
        execute(); 
    }//GEN-LAST:event_jTB_ExecuteActionPerformed

    private void mnu_Query_ExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_Query_ExecuteActionPerformed
        execute();
    }//GEN-LAST:event_mnu_Query_ExecuteActionPerformed

    private void mnu_Help_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_Help_AboutActionPerformed
        JOptionPane.showMessageDialog(null, "Program by: Daniel Wilson");
    }//GEN-LAST:event_mnu_Help_AboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab06GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab06GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab06GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab06GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab06GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_Grp_Degree;
    private javax.swing.ButtonGroup btn_Grp_Thesis;
    private javax.swing.JComboBox cbo_College;
    private javax.swing.JComboBox cbo_Country;
    private javax.swing.JComboBox cbo_Major;
    private javax.swing.JComboBox cbo_Zip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton jTB_Clear;
    private javax.swing.JButton jTB_Execute;
    private javax.swing.JButton jTB_Exit;
    private javax.swing.JButton jTB_Save;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnu_File_Clear;
    private javax.swing.JMenuItem mnu_File_Exit;
    private javax.swing.JMenuItem mnu_File_Save;
    private javax.swing.JMenuItem mnu_Help_About;
    private javax.swing.JMenuItem mnu_New_Graduate;
    private javax.swing.JMenuItem mnu_New_NonDegree;
    private javax.swing.JMenuItem mnu_New_Undergrad;
    private javax.swing.JMenuItem mnu_Query_Enter;
    private javax.swing.JMenuItem mnu_Query_Execute;
    private javax.swing.JRadioButton rad_MS;
    private javax.swing.JRadioButton rad_NonThesis;
    private javax.swing.JRadioButton rad_PhD;
    private javax.swing.JRadioButton rad_Thesis;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_College;
    private javax.swing.JTextField txt_FName;
    private javax.swing.JTextField txt_LName;
    private javax.swing.JTextField txt_MInit;
    private javax.swing.JTextField txt_PUID;
    private javax.swing.JTextField txt_State;
    // End of variables declaration//GEN-END:variables
}
