/*
 * THIS FILE WAS AUTOMATICALLY GENERATED BY NETBEANS.
 * THE ONLY REASON IT IS HERE FOR MY PURPOSES IS SO I CAN RUN THIS PROGRAM MORE EASILY
 * 
 * Author:     Daniel Wilson
 * Email:      Wilso509@purdue.edu
 * Class:      CNIT 325
 * Assignment: Lab 5
 */
package lab05;

/**
 *
 * @author Daniel
 */
public class Lab05 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        personGUI a = new personGUI(); 
        a.setVisible(true);
        Person b = new Person(); 
        
    }
    
}
